# Generated by Django 5.1.3 on 2024-12-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('manager', 'Manager')], default='student', max_length=10),
        ),
    ]
